# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GridDiag <- function(FUNvaluesInput, gridDimensionInput, gridNumberInput, maxdimensionInput, decompositionInput, libraryInput, locationInput, printInput) {
    invisible(.Call('TDA_GridDiag', PACKAGE = 'TDA', FUNvaluesInput, gridDimensionInput, gridNumberInput, maxdimensionInput, decompositionInput, libraryInput, locationInput, printInput))
}

Bottleneck <- function(Diag1, Diag2) {
    .Call('TDA_Bottleneck', PACKAGE = 'TDA', Diag1, Diag2)
}

Wasserstein <- function(Diag1, Diag2, p) {
    .Call('TDA_Wasserstein', PACKAGE = 'TDA', Diag1, Diag2, p)
}

