# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GridDiag <- function(FUNvalues, gridDim, maxdimension, decomposition, library, location, printProgress) {
    .Call('TDA_GridDiag', PACKAGE = 'TDA', FUNvalues, gridDim, maxdimension, decomposition, library, location, printProgress)
}

Bottleneck <- function(Diag1, Diag2) {
    .Call('TDA_Bottleneck', PACKAGE = 'TDA', Diag1, Diag2)
}

Wasserstein <- function(Diag1, Diag2, p) {
    .Call('TDA_Wasserstein', PACKAGE = 'TDA', Diag1, Diag2, p)
}

Kde <- function(X, Grid, h, weight, printProgress) {
    .Call('TDA_Kde', PACKAGE = 'TDA', X, Grid, h, weight, printProgress)
}

KdeDist <- function(X, Grid, h, weight, printProgress) {
    .Call('TDA_KdeDist', PACKAGE = 'TDA', X, Grid, h, weight, printProgress)
}

Dtm <- function(knnDistance, weightBound, r) {
    .Call('TDA_Dtm', PACKAGE = 'TDA', knnDistance, weightBound, r)
}

DtmWeight <- function(knnDistance, weightBound, r, knnIndex, weight) {
    .Call('TDA_DtmWeight', PACKAGE = 'TDA', knnDistance, weightBound, r, knnIndex, weight)
}

FiltrationDiag <- function(filtration, maxdimension, library, location, printProgress) {
    .Call('TDA_FiltrationDiag', PACKAGE = 'TDA', filtration, maxdimension, library, location, printProgress)
}

FunFiltration <- function(FUNvalues, cmplx) {
    .Call('TDA_FunFiltration', PACKAGE = 'TDA', FUNvalues, cmplx)
}

RipsFiltration <- function(X, maxdimension, maxscale, dist, library, printProgress) {
    .Call('TDA_RipsFiltration', PACKAGE = 'TDA', X, maxdimension, maxscale, dist, library, printProgress)
}

RipsDiag <- function(X, maxdimension, maxscale, dist, libraryFiltration, libraryDiag, location, printProgress) {
    .Call('TDA_RipsDiag', PACKAGE = 'TDA', X, maxdimension, maxscale, dist, libraryFiltration, libraryDiag, location, printProgress)
}

AlphaShapeFiltration <- function(X, printProgress) {
    .Call('TDA_AlphaShapeFiltration', PACKAGE = 'TDA', X, printProgress)
}

AlphaShapeDiagGudhi <- function(X, printProgress) {
    .Call('TDA_AlphaShapeDiagGudhi', PACKAGE = 'TDA', X, printProgress)
}

AlphaComplexFiltration <- function(X, printProgress) {
    .Call('TDA_AlphaComplexFiltration', PACKAGE = 'TDA', X, printProgress)
}

AlphaComplexDiagGudhi <- function(X, printProgress) {
    .Call('TDA_AlphaComplexDiagGudhi', PACKAGE = 'TDA', X, printProgress)
}

